### ISSUE TITLE
Instability with Sonoma

### ISSUE THREAD

**Issue by oseynnes** [bettar/miele-lxiv#107]
Sorry, I originally posted [this issue ](https://github.com/bettar/miele-lxiv-easy/issues/11#issue-2003925027)in the wrong place.

I use a MacBook Pro (M1, MacOS 14.1.1) and things have been fine so far but recently, Miele lxiv (9.35.132) started to freeze shortly after I had to re-install it.
Incidentally, I no longer get the right photometric interpretation of the images when they are imported.

EDIT: I did try changing: Preferences, General, JPEG compression, "For Color JPEG DICOM..."  as suggested but that did not help.
I'll try and re-install again and post back to check that the issue is not from the installation. Are there any preference files that I should make sure to remove?

**Comment by bettar** [comment]
It would have been better to have two distinct issues, one for the "freeze" and one for the "photometric interpretation" because it's difficult to imagine that the two things are related.

Is there a pattern in what happens before the "freeze" ? Is it random ? Is it happening 100% of the times ? Are there any error messages if you launch the app from Terminal ?

**Comment by oseynnes** [comment]
"Freeze" is not accurate, apologies. What happens is that some operations (like right-clicking on multiple images, or de-activating "For Color JPEG DICOM..." for example) take time and the CPU works at 100% (the GPU is not used but I guess that this is not intended for such tasks). Quitting the app also takes time.
As mentioned above, I'd like to re-install again and post back to check that the issue is not from the installation. Are there any preference files that I should make sure to remove?

**Comment by bettar** [comment]
when you launch the app from Terminal it prints out many things, including the location of the preference file. Note that because the app is sandboxed you probably won't be able to see that location in Finder, but it should be visible from Terminal

**Comment by oseynnes** [comment]
I did and got a clean uninstall I think. But when re-installing I get the same problem. Just clicking on the "Import" button freezes the app (this time for good) and I have to force-quit it.

**Comment by bettar** [comment]
So if you don't click "Import" it doesn't freeze ?

**Comment by oseynnes** [comment]
No, it does not.


On 23 Nov 2023, at 13:11, Alex Bettarini ***@***.***> wrote:



So if you don't click "Import" it doesn't freeze ?

**Comment by bettar** [comment]
It's hard to guess what is going on. So far you said you did a clean install (of macOS ? of the app? did you remove the preferences file ? did you delete the database directory ?) Then you said that if you don't click the Import button the app runs normally, and when you click Import it freezes. Which of the following two cases do you think is more likely ? The "freeze" is caused by:

1. a bug in miele-lxiv 
2. some problem with your machine configuration

Also, please launch the app from Terminal and report the messages printed out after you click Import.

Also, try changing the System settings, Security & privacy, Privacy to allow the app to access more system resources, for example "Full Disk Access" and "Files and Folders"

**Comment by oseynnes** [comment]
These were good hints! I store files on an external server (Onedrive) and Miele-lxiv did not have access to it. I could change that in the Security and privacy settings, thank you.

Should I close this issue and make a new one about the colour interpretation?


On 23 Nov 2023, at 15:20, Alex Bettarini ***@***.***> wrote:



It's hard to guess what is going on. So far you said you did a clean install (of macOS ? of the app? did you remove the preferences file ? did you delete the database directory ?) Then you said that if you don't click the Import button the app runs normally, and when you click Import it freezes. Which of the following two cases do you think is more likely ?

  1.  there is a bug in miele-lxiv
  2.  there is some problem with your machine configuration

Also, please launch the app from Terminal and report the messages printed out after you click Import.

Also, try changing the System settings, Security & privacy, Privacy to allow the app to access more system resources, for example "Full Disk Access" and "Files and Folders"

**Comment by oseynnes** [comment]
By the way, I tried unchecking "For Color JPEG DICOM..." again and this time I could restart Miele-lxiv. Now I get the right colour now. Not sure why.

Thanks for your help!


On 24 Nov 2023, at 09:46, Alex Bettarini ***@***.***> wrote:



Closed #107<https://github.com/bettar/miele-lxiv/issues/107> as completed.
