### ISSUE TITLE
Q/R window name display

### ISSUE THREAD

**Issue by robmclear** [bettar/miele-lxiv#115]
In the Q/R window, patient names are listed as FIRST LAST. Once retrieved, names are listed as LAST FIRST.  

<img width="1079" alt="Screenshot 2024-03-17 at 12 12 14 PM" src="https://github.com/bettar/miele-lxiv/assets/6690761/59c7e045-b8d2-4a5b-a51b-19bc83682aea">

**Comment by bettar** [comment]
Are you requesting that they should be both LAST FIRST, or both FIRST LAST ?

**Comment by robmclear** [comment]
Every system I’ve ever used has displayed patient names as LAST FIRST, so that would be my recommendation. 

-Rob

**Comment by bettar** [comment]
Thank you for the clarification. I started investigating the issue, which is remotely related to issue #91.
If you expect the order to be LAST FIRST, you are saying the Query results are wrong.
Can you please post a screenshot of one of the other systems that you've ever used, showing the result for the SAME Query that you posted above ?  I'm asking you this because I suspect that some servers don't encode the Patient Name correctly, for example they might put "GivenName FamilyName" in the field reserved to the FamilyName.

**Comment by robmclear** [comment]
Happy to help. Attached are images of queries from two unrelated servers hosted by different companies using the current versions of Horos and Miele, demonstrating the issue.

-Rob

￼￼￼￼

**Comment by bettar** [comment]
I received your email but there was no attachment of any screenshot.

**Comment by robmclear** [comment]
Trying again, I don’t have access to the same servers from here today, so this is one server queried with Horos and Miele showing the difference in name order. Other servers I have checked yield the same results.

**Comment by bettar** [comment]
Again I didn't get any screenshot attachments in the email, could you try adding them from the GitHub page like you did in your first message above ?

**Comment by robmclear** [comment]
Happy to help. Attached are images of queries from two unrelated servers hosted by different companies using the current versions of Horos and Miele, demonstrating the issue.

-Rob

<img width="1041" alt="Server A (Horos)" src="https://github.com/bettar/miele-lxiv/assets/6690761/e7d8143d-6214-4fb3-8b5b-ec8f43e19054">
<img width="985" alt="Server A (Miele)" src="https://github.com/bettar/miele-lxiv/assets/6690761/e8babbc4-b96c-4fb8-8ad7-1009f1828fed">
<img width="1040" alt="Server B (Horos)" src="https://github.com/bettar/miele-lxiv/assets/6690761/370c555b-aceb-4795-9798-1cdaa7fa7a7b">
<img width="987" alt="Server B (Miele)" src="https://github.com/bettar/miele-lxiv/assets/6690761/e279427e-35c7-49d9-b832-3bdd4700f418">

**Comment by bettar** [comment]
Which ones are the Miele-LXIV screenshots, the first and the third ?

**Comment by bettar** [comment]
The DICOM person name is structured as [Person Name Components](https://dicom.nema.org/medical/dicom/current/output/chtml/part19/sect_10.2.html) with FamilyName first.

Since issue #91 Miele-LXIV parses the person name using the DCMTK function [getFormattedNameFromString](https://support.dcmtk.org/docs/classDcmPersonName.html#aa7635519dff43d43e1e0e10252843f4c) for which the output format is "[namePrefix][ firstName][ middleName][ lastName][, nameSuffix]".

This is where the swap of first/last name order occurs. I agree that it is inconsistent with the table in the Database view, but hopefully it does a better parsing of more complex names, for example having all 5 components.

**Comment by robmclear** [comment]
First and third images are Horos, second and fourth images are Miele.  Apologies again, the info was in the file name but I guess it doesn't carry over when posted on Github.

**Comment by bettar** [comment]
The fix will be included in the next release. It will work as per your recommendation, with the additional benefit of also fixing the Query column "Institution".
